services:
  node-exporter-1:
    image: "quay.io/prometheus/node-exporter:latest"
    hostname: node-exporter-1
    ports:
      - "9101:9100"

  cadvisor:
    image: "ghcr.io/google/cadvisor:latest"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    ports:
      - "8080:8080"
    privileged: true
    devices:
      - /dev/kmsg

  local-opentelemetry-collector:
    image: "otel/opentelemetry-collector:0.146.1"
    volumes:
      - "./local-collector/config.yaml:/etc/otelcol/config.yaml"

  remote-opentelemetry-collector:
    image: "otel/opentelemetry-collector:0.146.1"
    ports:
      - "4318:4318"
      - "9464:9464"
    volumes:
      - "./remote-collector/config.yaml:/etc/otelcol/config.yaml"

  prometheus:
    image: "prom/prometheus:latest"
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/config.yaml:/etc/prometheus/prometheus.yml"
